### ISSUE TITLE
GitHub Personal Access Token is not set, neither programmatically, nor using env "GH_TOKEN"

### ISSUE THREAD

**Issue by maifeeulasad** [fiahfy/picty#66]
When I tried to build this it failed. 

Command : `yarn build`

Complete execution : 
```
yarn run v1.22.10
$ electron-builder
  • electron-builder  version=22.9.1 os=5.4.0-65-generic
  • loaded configuration  file=/home/mua/Desktop/picty/electron-builder.js
  • writing effective config  file=dist/builder-effective-config.yaml
  • packaging       platform=linux arch=x64 electron=11.1.1 appOutDir=dist/linux-unpacked
  • building        target=snap arch=x64 file=dist/picty_0.7.1_amd64.snap
  • building        target=AppImage arch=x64 file=dist/Picty-0.7.1.AppImage
  • application Linux category is set to default "Utility"  reason=linux.category is not set and cannot map from macOS docs=https://www.electron.build/configuration/linux
  • application Linux category is set to default "Utility"  reason=linux.category is not set and cannot map from macOS docs=https://www.electron.build/configuration/linux
  ⨯ GitHub Personal Access Token is not set, neither programmatically, nor using env "GH_TOKEN"
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by fiahfy** [comment]
By default, upload to github is included in the build process.

Try the following command.

```
$ yarn electron-builder -p never
```

**Comment by maifeeulasad** [comment]
@fiahfy Thanks, but.
how can I set up this token ? and what is it needed ?

**Comment by maifeeulasad** [comment]
can you share your `.travis.yml` ?

**Comment by fiahfy** [comment]
Build and upload artifacts in GitHub Actions.
`GH_TOKEN` is set to the github access token.
https://github.com/fiahfy/picty/blob/master/.github/workflows/electron.yml#L28

**Comment by maifeeulasad** [comment]
I've tried a lot, but I only get : `GH_TOKEN` **is not set**

![11](https://user-images.githubusercontent.com/29339330/111820784-19c6bd80-890c-11eb-8d90-cca714c09b4f.png)
![22](https://user-images.githubusercontent.com/29339330/111820791-1af7ea80-890c-11eb-8c7a-65b075904be6.png)

**Comment by fiahfy** [comment]
`GH_TOKEN` = `secrets.GITHUB_TOKEN` is provided automatically on GitHub Actions, so you don't need it if you want to build it yourself.

**Comment by maifeeulasad** [comment]
thanks and really appreciate your help and support. but it's my bad i couldn't resolve this problem.

**Comment by maifeeulasad** [comment]
The problem was when I was using `yarn release`, it was trying to push release into your repository. Where I don't have write access. So I changed the repository-url to mine, and everything is working. 

Thanks.
